

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'OperationMaintenance_Assistant_ZN' do
  # your other pod
  # ...

  pod 'Alamofire', '~> 5.0.0.beta.1'
  pod "ESPullToRefresh"
  pod 'HandyJSON', '~> 4.2.0'
  pod 'RealmSwift'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Kingfisher', '~> 5.0'


end

